apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-product
  namespace: prod
spec:
  selector:
    matchLabels:
      app: ms-product
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ms-product
    spec:
      containers:
        - name: ms-product
          image: mathiskrr/breizhsport-product:v0.1
          env:
            - name: PORT
              value: "4002"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: ms-product
                  key: DB-HOST
            - name: DB_DIALECT
              valueFrom:
                configMapKeyRef:
                  name: ms-product
                  key: DB-DIALECT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: ms-product
                  key: DB-NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: ms-product
                  key: DB-USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ms-product
                  key: DB_PASSWORD
          ports:
            - containerPort: 4002
          resources:
            requests:
              cpu: 100m
              memory: 150Mi
            limits:
              cpu: 150m
              memory: 200Mi
