apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-cart
  namespace: prod
spec:
  selector:
    matchLabels:
      app: ms-cart
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ms-cart
    spec:
      containers:
        - name: ms-cart
          image: mathiskrr/breizhsport-cart:develop
          env:
            - name: PORT
              value: "4001"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: ms-cart
                  key: DB-HOST
            - name: DB_DIALECT
              valueFrom:
                configMapKeyRef:
                  name: ms-cart
                  key: DB-DIALECT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: ms-cart
                  key: DB-NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: ms-cart
                  key: DB-USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ms-cart
                  key: DB_PASSWORD
          ports:
            - containerPort: 4001
          resources:
            requests:
              cpu: 100m
              memory: 150Mi
            limits:
              cpu: 150m
              memory: 200Mi